export const giftList1 = [
    {
        id: 1,
        img_url: require('./img/o1.png'),
        giftName: 'Xiaomi 14',
        jackpot: 10,
        competency: 300,
        flowingTimes: 5,
    },
    {
        id: 2,
        img_url: require('./img/o2.png'),
        giftName: 'Xiaomi 14 Ultra',
        jackpot: 10,
        competency: 300,
        flowingTimes: 5,
    },
    {
        id: 3,
        img_url: require('./img/o3.png'),
        giftName: 'Xiaomi 13T Pro',
        jackpot: 10,
        competency: 300,
        flowingTimes: 5,
    },
    {
        id: 4,
        img_url: require('./img/o4.png'),
        giftName: 'Xiaomi Watch S3',
        jackpot: 10,
        competency: 300,
        flowingTimes: 5,
    },
    {
        id: 5,
        img_url: require('./img/o5.png'),
        giftName: 'Xiaomi Watch 2 Pro',
        jackpot: 10,
        competency: 300,
        flowingTimes: 5,
    },
];
